import { NextResponse } from 'next/server';

export async function GET() {
  try {
    // Comprehensive user data with photos from the team spreadsheet
    const realUsers = [
      // Core team with individual photos
      { displayName: 'Joshua Long', photoURL: 'https://i.imgur.com/j9CbMP0.jpeg' },
      { displayName: 'Rocky Niger', photoURL: 'https://i.imgur.com/SbOwscP.jpeg' },
      { displayName: 'Samuel Robert Hernandez', photoURL: 'https://i.imgur.com/ec2APdS.jpeg' },
      { displayName: 'Richard Niger', photoURL: 'https://i.imgur.com/oqbE5D8.jpeg' },
      { displayName: 'Emmett Sheehy', photoURL: 'https://i.imgur.com/pYvrh5K.jpeg' },
      { displayName: 'Styles Freeman', photoURL: 'https://i.imgur.com/zs8Hmw7.jpeg' },
      { displayName: 'Joseph Niger', photoURL: 'https://i.imgur.com/k9rmlmu.jpeg' },
      { displayName: 'Odbayar Amgalan', photoURL: 'https://i.imgur.com/EAhbQmZ.png' },
      { displayName: 'Nathan Lockhart', photoURL: 'https://i.imgur.com/6vnOxn0.jpeg' },
      { displayName: 'James W Perry', photoURL: 'https://i.imgur.com/xqDvK7E.jpeg' },
      { displayName: 'Johnathan Halaufia-Martinez', photoURL: 'https://i.imgur.com/AelA3FG.jpeg' },
      { displayName: 'Joshua McCarty-Cruz', photoURL: 'https://i.imgur.com/YKS1nfK.jpeg' },
      { displayName: 'Ralph Bernard Joyner Jr', photoURL: 'https://i.imgur.com/9iX0TMM.jpeg' },
      { displayName: 'Jahmaal Osbourne', photoURL: 'https://i.imgur.com/nfdFU5X.jpeg' },
      { displayName: 'Isabella Engelman', photoURL: 'https://i.imgur.com/PFlF6ZN.jpeg' },
      { displayName: 'Jeffrey Allen Turner', photoURL: 'https://i.imgur.com/FwuZ53B.jpeg' },
      { displayName: 'Edeline Themistocle', photoURL: 'https://i.imgur.com/juW6mDL.jpeg' },
      
      // Team members with unique photos
      { displayName: 'Andrew Atkerson', photoURL: 'https://i.imgur.com/B5MIqFS.jpeg' },
      { displayName: 'Andrew Sidorenko', photoURL: 'https://i.imgur.com/PgnjVYb.jpeg' },
      { displayName: 'Andrea Rovayo', photoURL: 'https://i.imgur.com/fzF41qW.jpeg' },
      { displayName: 'Bella Engelman', photoURL: 'https://i.imgur.com/B5MIqFS.jpeg' },
      { displayName: 'Brandon Strommer', photoURL: 'https://i.imgur.com/w3HAaCa.jpeg' },
      { displayName: 'Bruno Giudici', photoURL: 'https://i.imgur.com/KWkZpMC.jpeg' },
      { displayName: 'Christopher Ahrens', photoURL: 'https://i.imgur.com/7b0niwU.jpeg' },
      { displayName: 'Jason Ryan May', photoURL: 'https://i.imgur.com/B5MIqFS.jpeg' },
      { displayName: 'Jose Alberto Ramos', photoURL: 'https://i.imgur.com/7NrJAUd.jpeg' },
      { displayName: 'Jonathan Shahar', photoURL: 'https://i.imgur.com/AcECuth.jpeg' },
      { displayName: 'Luke A Brown', photoURL: 'https://i.imgur.com/2I3Iut8.jpeg' },
      { displayName: 'Marcelo Guerra', photoURL: 'https://i.imgur.com/P2g1yAO.jpeg' },
      { displayName: 'Paul Andre Emden', photoURL: 'https://i.imgur.com/SEa5F5h.jpeg' },
      { displayName: 'Ryan Madden', photoURL: 'https://i.imgur.com/Oqto4Sl.jpeg' },
      { displayName: 'Sebastian Vizcarrondo', photoURL: 'https://i.imgur.com/45KQfQk.jpeg' },
      
      // Additional team members with shared professional photos
      { displayName: 'William Milian JR', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Nathan Audelo', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Nathan J Lockhart', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Michael Alexander Castillero', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'William Dominique  Ronveaux Tordion', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Daniel Blanco', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Nicholas  Renner', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Andres Carvallo', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Jared Zakreski', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Elvin Gonzalez Rodriguez', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Carlos Jimenez Carrion', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Alex Pagan Martinez', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Alexandra Marin Laurencio', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Amber Stanfield', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Anthony Sokolov', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Arelis Martinez Lebron', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Brandon Varner', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Christopher Costantino', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Christopher Greenidge', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Danijel Gnjatic', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Destiny Avel', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Dioses Abadin', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Edwin Salabarria Jr', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Emanuel Santana', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Ericka Gonzalez', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Garrett Allen', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Gavin Mattingly', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Grantas Balsys', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'John Sheehy', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Joseph E Alvarado', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Justin Alred', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Logan Lieser', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Lynden Weddas', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Maria Ullivarri', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Mariana Hernandez', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Nagesh Bueiz', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Nicholas Curry', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Nicholas Renner', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Priscila Zabala Peris', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Robert Skutecky', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Sabrina Olivos', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Sarah Duhamel', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Taylor Webber', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Todd Powell', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Trevor Smaw', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Tyler Schultheis', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      
      // Additional names that appear on leaderboard
      { displayName: 'Adrian Busjahn', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Alan Wamsley', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Aleksei Baguer', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Alvaro Pareja', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Andrew Harantha', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Angel Suarez', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Bayden Wilson', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Carson Frady', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Chance Spaulding', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Crystal Renovato', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Devonte Bass', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Emilio Emuriel', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Eric Rayle', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Gabrielle Noriega', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Gianmarco Papandrea', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Joseph Grabert', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Kenneth Burcham', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Larry Golden III', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Louis Wycoff', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Luis Aldama', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Martin Makowski', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Maxwell Joos', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Miles Setzer', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Nikki Mazzola', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Rhys Topo', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Ronald Julian Isaza Irreno (Dual)', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Samuel Rolon Rosado', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Sterling Giles', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' },
      { displayName: 'Stewart Fagans', photoURL: 'https://i.imgur.com/wlI3pCA.jpeg' }
    ];

    return NextResponse.json({ users: realUsers });
  } catch (error) {
    return NextResponse.json({ error: 'Failed to fetch users' }, { status: 500 });
  }
}
